version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 8081:8080
    environment:
      DB_HOST: db
      DB_NAME: db
      DB_USER: marinetraffic
      DB_PASS: marinetrafficpass
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/src
    #command: php -S api:8080 -t src/lumen/public
    restart: always

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: marinetraffic
      MYSQL_PASSWORD: marinetrafficpass
      MYSQL_ROOT_PASSWORD: root
    expose:
      - '3306'
    ports:
      - '3309:3306'
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
      - type: bind
        source: ./build/db/my.cnf
        target: /etc/mysql/my.cnf
      - ./build/db/scripts:/docker-entrypoint-initdb.d

  db_ui:
    container_name: db_ui
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always

volumes:
  db_data:
